"""sync schema

Revision ID: 4cb5136a66ad
Revises: 
Create Date: 2025-12-13 18:15:24.160273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cb5136a66ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('riasec_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pertanyaan', sa.String(length=255), nullable=False),
    sa.Column('dimensi', sa.String(length=1), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('nisn', sa.String(length=20), nullable=True),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('kelas', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_student', sa.Integer(), nullable=False),
    sa.Column('paket_prediksi', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['id_student'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_student', sa.Integer(), nullable=True),
    sa.Column('biologi', sa.Integer(), nullable=True),
    sa.Column('fisika', sa.Integer(), nullable=True),
    sa.Column('kimia', sa.Integer(), nullable=True),
    sa.Column('matematika', sa.Integer(), nullable=True),
    sa.Column('ekonomi', sa.Integer(), nullable=True),
    sa.Column('sosiologi', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_student'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('riasec_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_student', sa.Integer(), nullable=False),
    sa.Column('id_question', sa.Integer(), nullable=False),
    sa.Column('skor', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_question'], ['riasec_questions.id'], ),
    sa.ForeignKeyConstraint(['id_student'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('riasec_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_student', sa.Integer(), nullable=False),
    sa.Column('skor_R', sa.Integer(), nullable=False),
    sa.Column('skor_I', sa.Integer(), nullable=False),
    sa.Column('skor_A', sa.Integer(), nullable=False),
    sa.Column('skor_S', sa.Integer(), nullable=False),
    sa.Column('skor_E', sa.Integer(), nullable=False),
    sa.Column('skor_C', sa.Integer(), nullable=False),
    sa.Column('top3', sa.String(length=3), nullable=True),
    sa.ForeignKeyConstraint(['id_student'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('riasec_results')
    op.drop_table('riasec_answers')
    op.drop_table('report_scores')
    op.drop_table('recommendations')
    op.drop_table('students')
    op.drop_table('users')
    op.drop_table('riasec_questions')
    # ### end Alembic commands ###
